# Generated by Django 5.2.12 on 2026-04-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
