# Generated by Django 5.2.12 on 2026-04-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='planned_product_count',
            field=models.PositiveIntegerField(default=0, help_text='Use for display counts, coming soon colections'),
        ),
    ]
