# Generated by Django 5.2.12 on 2026-04-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_collection_planned_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
