# Generated by Django 5.2.12 on 2026-04-07 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_collection_image_collection_image_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionNarrativePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('label', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collection_narratives')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_panels', to='products.collection')),
            ],
            options={
                'ordering': ['panel_number'],
                'unique_together': {('collection', 'panel_number')},
            },
        ),
    ]
