# Generated by Django 5.2.12 on 2026-04-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/story'),
        ),
        migrations.AddField(
            model_name='collection',
            name='story_image_alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collection',
            name='story_text_primary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='story_text_secondary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='story_title',
            field=models.CharField(blank=True, default='A city remade', max_length=150),
        ),
    ]
